name: Pull Request

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Lint
        run: bunx nx affected -t lint

      - name: Test
        run: bunx nx affected -t test

  title:
    runs-on: ubuntu-latest
    steps:
      - name: Lint PR title
        uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        with:
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            :bangbang: We require pull request titles to follow the pattern: [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```

            ✅ A good example should be as follows:

            ```
            feat(ui): add button component
            ^    ^    ^
            |    |    |__ Subject
            |    |_______ Scope (optional)
            |____________ Type
            ```

      - name: Delete comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        with:
          header: pr-title-lint-error
          delete: true
