name: Setup Environment

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
        default: ubuntu-latest

jobs:
  setup:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --no-cache
